### ISSUE TITLE
Integrate c2spoon with spoon-gumtree-diff?

### ISSUE THREAD

**Issue by iamkeyur** [SpoonLabs/c2spoon#1]
I tried to make c2spoon work recently. It didn’t work for me. But, I will try again. I was wondering if I get it to work properly, how it can be integrated with spoon-gumtree-diff?

**Comment by tdurieux** [comment]
Hello,

c2spoon is a relatively old project that is probably not working anymore with the current version of Spoon.
I developed it for one specific subject of C that is used in IntroClass: https://repairbenchmarks.cs.umass.edu/IntroClass/. It is lacking support for `struct` for example. 

GumTree (https://github.com/GumTreeDiff/gumtree) is supporting C (https://github.com/GumTreeDiff/gumtree/wiki/Languages). I would suggest using this directly GumTree. You will get a much better result.
